accept User Prompt 'Enter user name : '
set verify off
@dbmspool
grant create session to &user;
grant select on dba_jobs to &user;
grant select on dba_jobs_running to &user;
grant select on v_$database to &user;
grant select on v_$nls_parameters to &user;
grant select on v_$parameter to &user;
grant select on v_$process to &user;
grant select on v_$session to &user;
grant select on v_$timer to &user;
grant select on v_$instance to &user;
grant create database link to &user;
grant create library to  &user;
grant create materialized view to &user;
grant create procedure to &user;
grant create sequence to &user;
grant create synonym to &user;
grant create table to &user;
grant create trigger to &user;
grant create type to &user;
grant create view to &user;
grant execute on dbms_alert to &user;
grant execute on dbms_application_info to &user;
grant execute on dbms_aq to &user;
grant execute on dbms_aqadm to &user;
grant execute on dbms_job to  &user;
grant execute on dbms_lock to  &user;
grant execute on dbms_pipe to  &user;
grant execute on dbms_refresh to  &user;
grant execute on dbms_rls to  &user;
create public synonym dbms_shared_pool for sys.dbms_shared_pool;
grant execute on dbms_shared_pool to  &user;
grant execute on dbms_sql to  &user;
grant execute on utl_file to  &user;
grant select on SYS.TRANSPORT_SET_VIOLATIONS to  &user;
grant create evaluation context to  &user;
grant create rule to  &user;
grant create job to  &user;
grant create rule set to  &user;
grant exp_full_database to  &user; 
grant alter tablespace to  &user;
grant manage tablespace to  &user;
grant execute on DBMS_FILE_TRANSFER to  &user;
grant execute on SYS.DBMS_TTS to  &user; 
grant execute on SYS.DBMS_DATAPUMP to  &user;
grant JAVAUSERPRIV to &user;
grant execute on dbms_scheduler to  &user;
create public synonym UTL_RECOMP for sys.UTL_RECOMP;
grant execute on UTL_RECOMP to &user;
grant execute on DBMS_MONITOR to &user;
grant select on dba_directories to &user;
grant execute on DBMS_CRYPTO to &user;
grant select on gv_$session to &user;
grant create any directory to &user;
grant select on SYS.DBA_SCHEDULER_RUNNING_JOBS to &user;
grant execute on sys.dbms_redact to &user; 
grant SELECT on sys.redaction_policies to &user; 
grant SELECT on sys.redaction_columns to &user; 
grant SELECT on sys.redaction_values_for_type_full to &user; 
set verify on