ALTER SESSION SET ddl_lock_timeout=300;
ALTER INDEX CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING_INDEX1 REBUILD PARTITION SYS_P4593062 TABLESPACE DELIVERYTRACKING_IDX_072020 NOLOGGING;
ALTER INDEX CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING_INDEX1 REBUILD PARTITION SYS_P4593063 TABLESPACE DELIVERYTRACKING_IDX_072020 NOLOGGING;
ALTER INDEX CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING_INDEX1 REBUILD PARTITION SYS_P4593064 TABLESPACE DELIVERYTRACKING_IDX_072020 NOLOGGING;
ALTER INDEX CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING_INDEX1 REBUILD PARTITION SYS_P4593065 TABLESPACE DELIVERYTRACKING_IDX_072020 NOLOGGING;
ALTER INDEX CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING_INDEX1 REBUILD PARTITION SYS_P4593066 TABLESPACE DELIVERYTRACKING_IDX_072020 NOLOGGING;





Jalankan tiap awal bulan :
ALTER SESSION SET ddl_lock_timeout=300;
--INDEX DEFAULT ATTRIBUT
ALTER INDEX CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING_INDEX1 MODIFY DEFAULT ATTRIBUTES TABLESPACE DELIVERYTRACKING_IDX_022021;
ALTER INDEX CAMPAIGN_TRACKING.CMS_TRACKINGSTREAM_IDX01 MODIFY DEFAULT ATTRIBUTES TABLESPACE TRACKINGSTREAM_IDX_022021;
ALTER INDEX CAMPAIGN_TRACKING.CMS_TRACKINGSTREAM_IDX02 MODIFY DEFAULT ATTRIBUTES TABLESPACE TRACKINGSTREAM_IDX_022021;

--TABLE DEFAULT ATTRIBUT
ALTER TABLE CAMPAIGN_TRACKING.CMS_TRACKINGSTREAM MODIFY DEFAULT ATTRIBUTES TABLESPACE TRACKINGSTREAM_022021;
ALTER TABLE CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING MODIFY DEFAULT ATTRIBUTES TABLESPACE DELIVERYTRACKING_022021;




