/*1. Pre-check 
Cross-check list tablespaces and Health check database.
2. Main Action
A. Create, Do Offline and Drop Tablespace Monthly

2.1. OPSELREP
** DT_RATEDATA_202202 (need min 90G)
CREATE TABLESPACE DT_RATEDATA_202204 DATAFILE '+DATA1' SIZE 1G AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
alter tablespace DT_RATEDATA_202204 add datafile '+DATA1' size 1G autoextend on next 300M maxsize 30G;
alter tablespace DT_RATEDATA_202204 add datafile '+DATA1' size 1G autoextend on next 300M maxsize 30G;
alter tablespace DT_RATEDATA_202204 add datafile '+DATA1' size 1G autoextend on next 300M maxsize 30G;
ALTER USER UREP1 QUOTA UNLIMITED ON DT_RATEDATA_202204;

** IDX_RATEDATA_202204
SQL> CREATE TABLESPACE IDX_RATEDATA_202204 DATAFILE '+DATA1' SIZE 1G AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
SQL> ALTER USER UREP1 QUOTA UNLIMITED ON IDX_RATEDATA_202204;

** Make Offline tablespace 
SQL> alter tablespace DT_RATEDATA_202110 OFFLINE;
SQL> alter tablespace IDX_RATEDATA_202110 OFFLINE;


** Drop Offline tablespace 
>> Check Tablespace with OFFLINE status :

SQL> select tablespace_name, status from dba_tablespaces where status='OFFLINE';
PROOL_SOAINFRA
PROBT_SOAINFRA
PROOLTBS_SOAINFRA
PROBTTBS_SOAINFRA
PROSYNC_SOAINFRA
PROSYNCTBS_SOAINFRA
PROTRY_SOAINFRA


>> Activity
SQL> Drop tablespace DT_RATEDATA_202109 INCLUDING CONTENTS AND DATAFILES;
SQL> Drop tablespace IDX_RATEDATA_202109 INCLUDING CONTENTS AND DATAFILES;
*/

2.2. OPICASMS19
** DT_RATEDATA_202204 (need min 90G)
CREATE TABLESPACE DT_RATEDATA_202204 DATAFILE '+DATAC5' SIZE 1G AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
alter tablespace DT_RATEDATA_202204 add datafile '+DATAC5' size 1G autoextend on next 300M maxsize 30G;
alter tablespace DT_RATEDATA_202204 add datafile '+DATAC5' size 1G autoextend on next 300M maxsize 30G;
ALTER USER ICACB_SMS1 QUOTA UNLIMITED ON DT_RATEDATA_202204;
ALTER USER ICACB_SMS2 QUOTA UNLIMITED ON DT_RATEDATA_202204;
ALTER USER ICACB_SMS3 QUOTA UNLIMITED ON DT_RATEDATA_202204;
ALTER USER ICACB_SMS4 QUOTA UNLIMITED ON DT_RATEDATA_202204;

** IDX_RATEDATA_202204
CREATE TABLESPACE IDX_RATEDATA_202204 DATAFILE '+DATAC5' SIZE 1G AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
ALTER USER ICACB_SMS1 QUOTA UNLIMITED ON IDX_RATEDATA_202204;
ALTER USER ICACB_SMS2 QUOTA UNLIMITED ON IDX_RATEDATA_202204;
ALTER USER ICACB_SMS3 QUOTA UNLIMITED ON IDX_RATEDATA_202204;
ALTER USER ICACB_SMS4 QUOTA UNLIMITED ON IDX_RATEDATA_202204;

** Make Offline tablespace 
SQL> alter tablespace DT_RATEDATA_202110 OFFLINE;
SQL> alter tablespace IDX_RATEDATA_202110 OFFLINE;

** Drop Offline tablespace 
>> Check Tablespace with OFFLINE status :
SQL> select tablespace_name, status from dba_tablespaces where status='OFFLINE';

>> Activity
SQL> Drop tablespace DT_RATEDATA_202109 INCLUDING CONTENTS AND DATAFILES;
SQL> Drop tablespace IDX_RATEDATA_202109 INCLUDING CONTENTS AND DATAFILES;

/*
2.3.OPHPOINT
** TBS_PART_TBL_POIN_202204 (need min 100G)
SQL> CREATE TABLESPACE TBS_PART_TBL_POIN_202204 DATAFILE '+DATA1' SIZE 1G AUTOEXTEND ON NEXT 100M MAXSIZE 25G;
SQL> alter tablespace TBS_PART_TBL_POIN_202204 add datafile '+DATA1' size 1G autoextend on next 300M maxsize 25G;
SQL> alter tablespace TBS_PART_TBL_POIN_202204 add datafile '+DATA1' size 1G autoextend on next 300M maxsize 25G;
SQL> alter tablespace TBS_PART_TBL_POIN_202204 add datafile '+DATA1' size 1G autoextend on next 300M maxsize 25G;
SQL> ALTER USER NEWTSPOIN QUOTA UNLIMITED ON TBS_PART_TBL_POIN_202204;

** Make Offline tablespace 
SQL> alter tablespace TBS_PART_TBL_POIN_202012 OFFLINE;

** Drop Offline tablespace 
>> Check Tablespace with OFFLINE status :
SQL> select tablespace_name, status from dba_tablespaces where status='OFFLINE';

>> Activity
SQL> Drop tablespace TBS_PART_TBL_POIN_202011 INCLUDING CONTENTS AND DATAFILES;
*/


2.5 OPCMC
--Change default attribute
ALTER INDEX CAMPAIGN_TRACKING.CMS_DELIVERYTRACKING_INDEX1 MODIFY DEFAULT ATTRIBUTES TABLESPACE DELIVERYTRACKING_IDX_042022; 
ALTER INDEX CAMPAIGN_TRACKING.CMS_TRACKINGSTREAM_IDX01 MODIFY DEFAULT ATTRIBUTES TABLESPACE TRACKINGSTREAM_IDX_042022; 
ALTER INDEX CAMPAIGN_TRACKING.CMS_TRACKINGSTREAM_IDX02 MODIFY DEFAULT ATTRIBUTES TABLESPACE TRACKINGSTREAM_IDX_042022; 
--selesai team apps create partisi index tracking stream nya di unusable 
select 'alter index '||index_owner||'.'||index_name||' modify partition '||partition_name||' UNUSABLE;' 
from dba_ind_partitions 
where tablespace_name ='TRACKINGSTREAM_IDX_042022'
and status='USABLE';

ALTER SESSION set ddl_lock_timeout=360;
--hasil query diatas


** TRACKINGSTREAM_042022 (need min 30G)
SQL> CREATE TABLESPACE TRACKINGSTREAM_042022 DATAFILE '+DATAC1' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
SQL> ALTER USER CAMPAIGN_TRACKING QUOTA UNLIMITED ON TRACKINGSTREAM_042022;

** TRACKINGSTREAM_IDX_042022
SQL> CREATE TABLESPACE TRACKINGSTREAM_IDX_042022 DATAFILE '+DATAC1' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
SQL> ALTER USER CAMPAIGN_TRACKING QUOTA UNLIMITED ON TRACKINGSTREAM_IDX_042022;

** DELIVERYTRACKING_042022 (need min 30G)
SQL> CREATE TABLESPACE DELIVERYTRACKING_042022 DATAFILE '+DATAC1' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
SQL> ALTER USER CAMPAIGN_TRACKING QUOTA UNLIMITED ON DELIVERYTRACKING_022022;

** DELIVERYTRACKING_IDX_042022
SQL> CREATE TABLESPACE DELIVERYTRACKING_IDX_042022 DATAFILE '+DATAC1' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 30G;
SQL> ALTER USER CAMPAIGN_TRACKING QUOTA UNLIMITED ON DELIVERYTRACKING_IDX_042022;

4. Cross-check 
Cross-check tablespaces and Health check Database