SET DB OPEN READ ONLY

1. SHUTDOWN MRP.
SQL> ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL;

2. OPEN THE DATABASE.
SQL> ALTER DATABASE OPEN READ ONLY;

3. ACTIVATE MRP.
SQL> ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT FROM SESSION;



------------------------------------------------------------------------------------------------------------------------


MOUNTING DB -- standby yang sedang Open.

1.	SHUTDOWN MRP
SQL> ALTER DATABASE RECOVER MANAGED STANDBY DATABASE CANCEL;


2. SHUTDOWN INSTANCE
$srvctl status instance -d OPAPM62B -i OPAPM62B1
$srvctl stop instance -d OPAPM62B -i OPAPM62B1

3. START MOUNTS
$srvctl start instance -d OPAPM62B -i OPAPM62B1 -o mount

4. ACTIVATE MRP
ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE DISCONNECT FROM SESSION;
