*DOMEVN - Multi JDBC ***
(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=off)(CONNECT_TIMEOUT=2)(RETRY_COUNT=2)(RETRY_DELAY=2)
(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=exa62bsda-scan)(PORT=1521)))
(CONNECT_DATA=(SERVICE_NAME=DOMEVN)))


*DOMEVN - Weblogic Multi datasource*
DOMEVN Datasource 1 – exa62B - primary
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMEVN)))


DOMEVN Datasource 2 – TBS - standby
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exa62bsda-scan)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMEVN)))



*DOMODD - Multi JDBC ***
(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=off)(CONNECT_TIMEOUT=2)(RETRY_COUNT=2)(RETRY_DELAY=2)
(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=exa82absdp-scan1)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=DOMODD)))


*DOMODD - Weblogic Multi datasource*
DOMODD Datasource 1 – exa82 - primary
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exa82absdp-scan1)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMODD)))


DOMODD Datasource 2 – TBS - standby
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMODD)))


====================================================================================================

C2PEVN - multi
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=off)(CONNECT_TIMEOUT=2)(RETRY_COUNT=2)(RETRY_DELAY=2)
(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62a-scan)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=exaimcpdb-scan)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=C2PEVN)))

 
DOMODD - multi
(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=off)(CONNECT_TIMEOUT=2)(RETRY_COUNT=2)(RETRY_DELAY=2)
(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=exa62bsda-scan)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=DOMODD)))

 

DOMEVEN - multi
(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=off)(CONNECT_TIMEOUT=2)(RETRY_COUNT=2)(RETRY_DELAY=2)
(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521))
(ADDRESS=(PROTOCOL=TCP)(HOST=exa62bsda-scan)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=DOMEVEN)))

 
DOMODD BSD-primary
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exa62bsda-scan)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMODD)))


DOMODD TBS-secondary
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMODD)))


DOMEVN TBS-primary
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exapdb62b-scan)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMEVEN)))

 

DOMEVN BSD-secondary
jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=on)
(ADDRESS=(PROTOCOL=TCP)(HOST=exa62bsda-scan)(PORT=1521))
(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=DOMEVEN)))