1. Check CONSTRAINCT

SELECT OWNER, TABLE_NAME, STATUS, CONSTRAINT_NAME 
FROM ALL_CONSTRAINT 
WHERE STATUS='DISABLED' 
AND TABLE_NAME='TABLE';


#KALAU ERROR CONSTRAINT IMPORT

1. Check Constraintnya
SELECT * FROM dba_cons_columns WHERE table_name = 'CONTENTS_2022';


2. Check Type Nya  
col owner for a30
col constraint_name for a30
col constraint_type for a30
col table_name for a30
select owner, CONSTRAINT_NAME, CONSTRAINT_TYPE, TABLE_NAME from dba_constraints
where table_name like 'CONTENTS%';

3. kalau perlu, create (ambil ddl dari table lama)

ALTER TABLE "TRIPWIRE"."CONTENTS" ADD PRIMARY KEY ("OID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "TRIPWIRE_TBS_LOB"  ENABLE;
  
  
  