
Note!
Kalau create table dan constraint_name already exist, gpp dibedain aja

------------------------------------------------------------------------------------------------------------------------

---SERVER_CACHE
CREATE TABLE "NFT_OMS_USER"."SERVER_CACHE" ( 
    "CACHE_ID" NUMBER(20) NOT NULL , 
    "CACHE_NAME" VARCHAR2(100 CHAR) NOT NULL , 
    "CACHE_TYPE" VARCHAR2(50 CHAR), 
    "DATA" BLOB NOT NULL , 
    "LAST_UPDATED_ON" TIMESTAMP(6) WITH TIME ZONE, 
    "CACHE_VALIDITY" VARCHAR2(1 CHAR) NOT NULL 
    ) 
    TABLESPACE "FOM_OMS_PRD" 
    PCTFREE 10 INITRANS 1 MAXTRANS 255 
    STORAGE ( INITIAL 64K BUFFER_POOL DEFAULT) 
    LOGGING NOCOMPRESS 
    LOB ("DATA") 
    STORE AS SECUREFILE ( 
        TABLESPACE "FOM_OMS_PRD" 
        RETENTION AUTO KEEP_DUPLICATES NOCOMPRESS 
        STORAGE ( INITIAL 104K BUFFER_POOL DEFAULT) NOCACHE LOGGING )
insert into PRDP_OMS_USER.SERVER_CACHE as select * from NFT_OMS_USER.DATA_MODEL_RELATION;


------------------------------------------------------------------------------------------------------------------------

--DATA_MODEL_RELATION
CREATE TABLE "NFT_OMS_USER"."DATA_MODEL_RELATION" ( 
    "RELID" VARCHAR2(200 CHAR), 
    "PARENTID" VARCHAR2(200 CHAR) NOT NULL , 
    "DATAID" VARCHAR2(200 CHAR) NOT NULL , 
    "MODELTYPE" VARCHAR2(200 CHAR) NOT NULL , 
    PRIMARY KEY ("RELID") VALIDATE 
    ) 
    TABLESPACE "FOM_OMS_PRD" 
    PCTFREE 10 INITRANS 1 MAXTRANS 255 
    STORAGE ( INITIAL 64K BUFFER_POOL DEFAULT) 
    LOGGING NOCOMPRESS 
INSERT INTO PRDP_OMS_USER.DATA_MODEL_RELATION as select * from NFT_OMS_USER.DATA_MODEL_RELATION;