CREATE OR REPLACE TRIGGER CIS.T_IC_BUCKET_DELTA_INSERT
AFTER INSERT
ON CIS.INVOICE_CHANNEL_BUCKET
REFERENCING NEW AS New OLD AS Old FOR EACH ROW 
DECLARE
	tmpVar NUMBER;
BEGIN
	tmpVar := 0;
	INSERT INTO EIMADMIN.T_INVOICE_CHANNEL_BUCKET_DELTA (ID, ACTION) VALUES (:NEW.ID, 'INSERT');
	EXCEPTION WHEN OTHERS THEN -- Consider logging the error and then re-raise
	RAISE;
END T_IC_BUCKET_DELTA_INSERT;
/