#drop table
DROP TABLE TABLE_NAME CASCADE CONSTRAINTS;

#drop index
DROP INDEX USER_NAME.INDE_NAME;


#drop index_partition
SELECT 'DROP INDEX '||INDEX_OWNER||'.'||INDEX_NAME||' DROP PARTITION '||PARTITION_NAME||';' 
FROM dba_ind_PARTITIONS 
WHERE TABLESPACE_NAME in ('TY_ATPUPTPNT_201304_A');


#drop sub_partition
SELECT 'ALTER TABLE '||TABLE_OWNER||'.'||TABLE_NAME||' DROP SUBPARTITION '||SUBPARTITION_NAME||';' 
FROM DBA_TAB_SUBPARTITIONS 
WHERE TABLESPACE_NAME in ('TY_ATPUPTPNT_201304_A');