1. rename CUSTOMER_KPI_RL to CUSTOMER_KPI_RL_OLD

SQL> RENAME table SCV_LOAD_USR.CUSTOMER_KPI_RL TO SCV_LOAD_USR.CUSTOMER_KPI_RL_OLD;



2. rename CUSTOMER_KPI_RL_NEW to CUSTOMER_KPI_RL

SQL> RENAME table SCV_LOAD_USR.CUSTOMER_KPI_RL_NEW TO SCV_LOAD_USR.CUSTOMER_KPI_RL;

