set lines 999
set pages 999
col grantee for a32
col owner for a32
col table_name for a32
col grantor for a20
col privilege for a16
col grantable for a16
SELECT * FROM DBA_TAB_PRIVS
where GRANTEE in ('TSEL_VERONADM')
and type='TABLE';

set lines 999
set pages 999
col grantee for a32
col owner for a32
col table_name for a32
col grantor for a20
col privilege for a16
col grantable for a16
SELECT GRANTEE, OWNER, PRIVILEGE FROM DBA_TAB_PRIVS
where GRANTEE in ('FCC114');
and PRIVILEGE like '%DBMS%';


set colsep '|'
set lines 999
set pages 999
col grantee for a32
col privilege for a40
SELECT  distinct GRANTEE, PRIVILEGE
FROM DBA_TAB_PRIVS
where type='TABLE';





SELECT OWNER, SEGMENT_NAME FROM DBA_SEGMENTS 
WHERE OWNER IN ('SAP')
AND SEGMENT_TYPE='TABLE'
GROUP BY OWNER, SEGMENT_NAME;


--DEFAULT UNTUK USER
GRANT CONNECT, RESOURCE TO USERNAME;
GRANT CONNECT TO PROAPP, EPC;
GRANT RESOURCE TO PROAPP, EPC;

--REVOKE
REVOKE CREATE TABLESPACE FROM USERNAME;

--TABLE
GRANT CREATE TABLE TO USERNAME;
GRANT SELECT ANY TABLE TO USERNAME;
GRANT DROP ANY TABLE TO USERNAME;

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, READ, DEBUG, FLASHBACK ON OWNER.TABLE TO USER_NAME;

--SELECT
GRANT SELECT ON SCHEMA.TABLE TO USERNAME;



--UNTUK AMBIL LIST TABLE NYA.
SELECT 'GRANT SELECT ON CA_IDM.'||TABLE_NAME||' TO INTERNAL_AUDIT;' 
FROM DBA_TABLES WHERE OWNER='CA_IDM'; 


--TEST COUNT --MASUK PAKE USER APPS NYA DULU
SELECT COUNT(1) FROM SHCEMA.TABLE_NAME;


--SELECT ON ARCHIVE LOG USAGE, INSTANCE STATUS, TABLESPACE SPACE USED
GRANT SELECT ON DBA_DATA_FILES TO USERNAME;
GRANT SELECT ON DBA_USERS TO USERNAME;
GRANT SELECT ON DBA_FREE_SPACE TO USERNAME;
GRANT SELECT ON V_$INSTANCE TO USERNAME;
GRANT SELECT ON V_$LOG TO USERNAME;
GRANT SELECT ON V_$LOG_HISTORY TO USERNAME;


--SELECT, UPDATE, INSERT, DELETE
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA.OBJECT TO USERNAME;


--CREATE TRIGGER
GRANT CREATE TRIGGER TO USERNAME;


--QUOTA UNLIMITED
ALTER USER USERNAME QUOTA UNLIMITED ON TABLESPACE_NAME;



--CREATE EXTERNAL JOB
GRANT CREATE EXTERNAL JOB TO USERNAME;


--INDEX
GRANT CREATE INDEX TO USERNAME;
GRANT CREATE ANY INDEX TO USERNAME;

--SELECT TABLE / SELET SPESIFIK TABLE
GRANT SELECT SCHEMA.TABLE TO USERNAME;


--CREATE DB_LINK
GRANT CREATE DATABASE LINK TO USERNAME;
GRANT CREATE PUBLIC DATABASE LINK TO USERNAME;


--REFERENCES
GRANT REFERENCES ON SCHEMA.TABLE TO USERNAME;
SELECT 'GRANT SELECT ON '||OWNER||'.'||TABLE_NAME||' TO useryangakandigrant;' FROM DBA_TABLES WHERE OWNER='owneruseryangdicari';
SELECT 'GRANT SELECT ON '||OWNER||'.'||VIEW_NAME||' TO useryangakandigrant;' FROM DBA_VIEWS WHERE OWNER='owneruseryangdicari';
SELECT 'GRANT SELECT ON '||OWNER||'.'||OBJECT_NAME||' TO NIMMON;' FROM DBA_OBJECTS WHERE OWNER='PGATEENH' AND OBJECT_TYPE='TABLE';

CTCSYS, CTC_PREFUT2_USR, CTC_PREFUT_USR

--SYNONYM
GRANT CREATE PUBLIC SYNONYM TO USERNAME; 
GRANT CREATE SYNONYM TO EDWMDLRO1; 
GRANT CREATE ANY SYNONYM TO USERNAME; 
GRANT DROP ANY SYNONYM TO USERNAME; 
GRANT DROP PUBLIC SYNONYM TO USERNAME; 

--GRANT
GRANT CREATE ANY SYNONYM TO CTCSYS;

--CREATE SYNONYM
PUBLIC : GRANT CREATE PUBLIC SYNONYM TO PROAPP, EPC;
PRIVATE: GRANT CREATE ANY SYNONYM TO CTCSYS;


--VIEW 
GRANT CREATE VIEW TO USERNAME;
GRANT CREATE ANY VIEW TO USERNAME;
GRANT DROP ANY VIEW TO USERNAME;


--grant ke socket java nya
grant javasyspriv to PROD_OSB_CRM;
grant javadebugpriv to PROD_OSB_CRM;


--SEQUENCE 
GRANT CREATE SEQUENCE TO USERNAME;
GRANT CREATE ANY SEQUENCE TO USERNAME;


--MATERIALIZED
GRANT CREATE MATERIALIZED VIEW TO USERNAME;
GRANT CREATE ANY MATERIALIZED VIEW TO USERNAME;
GRANT ALTER ANY MATERIALIZED VIEW TO USERNAME;
GRANT DROP ANY MATERIALIZED VIEW TO USERNAME;


--TYPE
GRANT CREATE TYPE TO USERNAME;
GRANT CREATE ANY TYPE TO USERNAME;



--EXP_FULL_DATABASE/EXPORT/IMPORT
GRANT EXP_FULL_DATABASE TO USERNAME;
GRANT IMP_FULL_DATABASE TO USERNAME;


--ALTER USER
ALTER USER PROAPP, EPC DEFAULT ROLE NONE;
  
 

--DIMENSION
GRANT CREATE DIMENSION TO USERNAME;


--INDEXTYPE
GRANT CREATE INDEXTYPE TO USERNAME;


--JOB
GRANT CREATE JOB TO USERNAME;
GRANT CREATE JOBS TO USERNAME;


--LIBRARY
GRANT CREATE LIBRARY TO USERNAME;


--PROCEDURE
GRANT CREATE PROCEDURE TO USERNAME;
GRANT EXECUTE ON OWNER.PKG.PROCEDURE TO <USERNAME>;
GRANT EXECUTE ON EPC.EPCPOSTIMPORT TO EPC;
Note!--untuk grant function and package, cukup grant procedure


--PROFILE
GRANT CREATE PROFILE TO USERNAME;

--GRANT READ, WRITE ON DIRECTORY
GRANT READ, WRITE ON DIRECTORY DIR_NAME TO USER;
CREATE DIRECTORY TKOMS01_EXPDP AS '/TKOMS01/ORAVL99/ORACLE/EXPDP';
GRANT READ, WRITE ON DIRECTORY TKOMS01_EXPDP TO EXP_FULL_DATABASE;


--QUOTA
ALTER USER TKOMS QUOTA UNLIMITED ON DATAL01;
ALTER USER SIEBEL QUOTA UNLIMITED ON SBL_HIS_IDX;

--GENERATE AWR
GRANT SELECT ANY DICTINONARY TO NEW_USER;
GRANT CREATE SESSION TO NEW_USER;
GRANT EXECUTE ON DBMS_WORKLOAD_REPOSITORY TO NEW_USER;


--GRANT SCHEDULER
grant create job to APPS;
grant execute on DBMS_SCHEDULER to APPS;
grant execute on DBMS_ISCHED to APPS;
