--Check PROFILE
col profile for a30
col resource_name for a30		 
col resource for a30
col limit for a30
set lines 300
set pages 20
select * from dba_profiles where profile ='LEVEL2';


---------------------------------------------------------------------------------------------------------------------

--Check DDL PROFILE
select dbms_metadata.get_ddl('PROFILE','LEVEL1') from dual;

---------------------------------------------------------------------------------------------------------------------

--ASSIGN PROFILE TO USER
alter user PRE2_IRISAPP profile LEVEL2; 


--PROFILE LEVEL 1
CREATE PROFILE LEVEL1 LIMIT
SESSIONS_PER_USER 1
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME UNLIMITED
LOGICAL_READS_PER_SESSION UNLIMITED
LOGICAL_READS_PER_CALL UNLIMITED
COMPOSITE_LIMIT UNLIMITED
PRIVATE_SGA UNLIMITED
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LIFE_TIME 60
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_REUSE_MAX 12
PASSWORD_LOCK_TIME UNLIMITED
PASSWORD_GRACE_TIME 12
PASSWORD_VERIFY_FUNCTION NULL;



--PROFILE LEVEL 2
CREATE PROFILE LEVEL2 LIMIT
SESSIONS_PER_USER UNLIMITED
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME UNLIMITED
LOGICAL_READS_PER_SESSION UNLIMITED
LOGICAL_READS_PER_CALL UNLIMITED
COMPOSITE_LIMIT UNLIMITED
PRIVATE_SGA UNLIMITED
FAILED_LOGIN_ATTEMPTS UNLIMITED
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_REUSE_MAX UNLIMITED
PASSWORD_LOCK_TIME UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION NULL;


--ALTER PROFILE
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME  UNLIMITED;


--ALTER PROFILE DEFAULT
ALTER PROFILE DEFAULT LIMIT
SESSIONS_PER_USER UNLIMITED
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
IDLE_TIME UNLIMITED
LOGICAL_READS_PER_SESSION UNLIMITED
LOGICAL_READS_PER_CALL UNLIMITED
COMPOSITE_LIMIT UNLIMITED
PRIVATE_SGA UNLIMITED
FAILED_LOGIN_ATTEMPTS UNLIMITED
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_REUSE_MAX UNLIMITED
PASSWORD_LOCK_TIME UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
PASSWORD_VERIFY_FUNCTION NULL;

---------------------------------------------------------------------------------------------------------------------


--MENGHAPUS PROFILE
DROP PROFILE PROFILE_NAME CASCADE;

Note!--setelah profile dihapus, user yang di-assign ke profile tersebut akan dikembalikan ke profile default.
